VehicleRentingSystemWeb/Areas/User/Controllers/CityController.cs
using VehicleRentingSystem.DataAccess;
using VehicleRentingSystem.DataAccess.Repository.IRepository;
using VehicleRentingSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace VehicleRentingSystemWeb.Areas.User.Controllers
{
    [Area("User")]
    public class CityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private object cityFromDbFirst;

        public CityController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<City> objCityList = _unitOfWork.City.GetAll();
            return View(objCityList);
        }
        //GET
        public IActionResult Create()
        {

            return View();
        }

        //POST 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(City obj)
        {
            
            if (ModelState.IsValid)
            {
                _unitOfWork.City.Add(obj);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        //Edit controller
        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.Categories.Find(id);
            var cityFromDbFirst = _unitOfWork.City.GetFirstOrDefault(u=>u.Id==id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (cityFromDbFirst == null)
            {
                return NotFound();
            }

            return View(cityFromDbFirst);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(City obj)
        {
            
            if (ModelState.IsValid)
            {
                _unitOfWork.City.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //Delete controller
        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
           // var categoryFromDb = _db.Categories.Find(id);
            var cityFromDbFirst = _unitOfWork.City.GetFirstOrDefault(u=>u.Id==id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (cityFromDbFirst == null)
            {
                return NotFound();
            }

            return View(cityFromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.City.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.City.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

VehicleRentingSystemWeb/Areas/User/Controllers/Post_CarController.cs
using VehicleRentingSystem.DataAccess;
using VehicleRentingSystem.DataAccess.Repository.IRepository;
using VehicleRentingSystem.Models;
using Microsoft.AspNetCore.Mvc;
using VehicleRentingSystem.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Linq.Expressions;

namespace VehicleRentingSystemWeb.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    
    public class Post_CarController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private object postCarFromDbFirst;
        public Bid Bid { get; set; }

        public Post_CarController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        
        public IActionResult Index()
        {
            IEnumerable<Post_Car> objPostList = _unitOfWork.Post_Car.GetAll();

            
            foreach(var item in objPostList)
            {
                //remaining time counting
                DateTime dateTime = DateTime.Now;

                TimeSpan remainingTime = dateTime.Subtract(item.TargetTime);


                if (remainingTime.Hours==0 && remainingTime.Minutes<0 || remainingTime.Hours==1 && remainingTime.Minutes<0)
                {
                    item.DewTime = Math.Abs(remainingTime.Minutes);
                }
                else
                {
                    item.DewTime = 0;
                    item.TimeOver = true;
                }

                //remaining time counting end


                var post = _unitOfWork.Bid.GetAll(u => u.PostId==item.Id);
                foreach(var item2 in post)
                {
                    if (item2.Confirmed == true)
                    {
                        
                        item.Confirm = true;
                    }
                }
            }

            PostVM postVM = new()
            {
                
                objPostCart = objPostList.OrderByDescending(u=>u.Id),

            };
            
           
            return View(postVM);
        }

        

         
        //GET
        public IActionResult Create()
        {


            return View();
        }

        //POST 
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize]
        public IActionResult Create(Post_Car obj)
        {
            //getting logged user id

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end

            //countDown timer
            DateTime dateTime= DateTime.Now;
            obj.PostTime = dateTime;
            obj.TargetTime= dateTime.AddMinutes(30);

            //countDown timer end

            obj.ApplicationUserId = claim.Value;

          
                _unitOfWork.Post_Car.Add(obj);
                _unitOfWork.Save();
               

            return RedirectToAction(nameof(Index));

        }

        

        public IActionResult Auction(int postId)
        {
            double? lowest;
            IEnumerable<Bid>? bidList = _unitOfWork.Bid.GetAll(u => u.PostId == postId);
            if (bidList.Count() != 0)
            {
                lowest = bidList.Min(u => u.Bidding);
            }
            else
            {
                lowest = 0;
            }

           

            Bid bid = new Bid()
            {
                PostId = postId,
               MinBid=lowest,
                

        };

  
            return View(bid);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize]
        public IActionResult Auction(Bid bid)
        {
            //getting logged user id

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end

            bid.ApplicationUserId = claim.Value;

            
            _unitOfWork.Bid.Add(bid);
            
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        
        public IActionResult Plus(Bid bidObj,  int postId)
        {
            //getting logged user id

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end

            bidObj.ApplicationUserId = claim.Value;
            
            IEnumerable<Bid> bidsFromDb = _unitOfWork.Bid.GetAll(u => u.PostId == postId);
            int minBid = bidsFromDb.Min(u => u.Bidding);

            bidObj.Bidding=minBid+100;
            _unitOfWork.Bid.Add(bidObj);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Minus(Bid bidObj, int postId)
        {
            //getting logged user id

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end

            bidObj.ApplicationUserId = claim.Value;
            

            IEnumerable<Bid> bidsFromDb = _unitOfWork.Bid.GetAll(u => u.PostId == postId);
            int minBid = bidsFromDb.Min(u => u.Bidding);

            bidObj.Bidding = minBid - 100;
            _unitOfWork.Bid.Add(bidObj);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult BiddingHistory(int postId)
        {
            IEnumerable<Bid> biddings = _unitOfWork.Bid.GetAll(u => u.PostId == postId, includeProperties: "ApplicationUser");
          
           // return View(bidHistory);

            BiddingHistoryVM biddingHistory = new()
            {
                bidHistory = _unitOfWork.Bid.GetAll(u => u.PostId == postId, includeProperties: "ApplicationUser"),
                
            };
            foreach (var bookedChecking in biddings)
            {
                if (bookedChecking.Confirmed == true)
                {
                    biddingHistory.booked = true;
                }
                //else
                //{
                //    biddingHistory.booked = false;
                //}
               
            }

            return View(biddingHistory);
        }


       



        public IActionResult Confirm(int bidId)
        {
            //getting logged user id

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end
            var bidItem = _unitOfWork.Bid.GetFirstOrDefault(u => u.Id == bidId);
            var postOwner = _unitOfWork.Post_Car.GetFirstOrDefault(u => u.Id == bidItem.PostId);
            if (postOwner.ApplicationUserId == claim.Value)
            {
                bidItem.Confirmed = true;
                _unitOfWork.Bid.Update(bidItem);
                _unitOfWork.Save();
                TempData["success"] = "Confirmed successfully";
            }
            else
            {
                //throw new Exception("You dont have right to confirm");
                TempData["error"] = "You are not allowed";
            }

            return RedirectToAction(nameof(BiddingHistory));

            
        }

        //Summary

        public IActionResult Summary(int postId)
        {
            Post_Car post=_unitOfWork.Post_Car.GetFirstOrDefault(u => u.Id == postId, includeProperties: "ApplicationUser");
            Bid bidding=_unitOfWork.Bid.GetFirstOrDefault(u=>u.PostId==postId && u.Confirmed==true, includeProperties: "ApplicationUser");
            SummaryVM summary = new()
            {
                post= post,
                bid= bidding,
            };

            return View(summary);
        }

    }
}

VehicleRentingSystemWeb/Areas/User/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VehicleRentingSystem.DataAccess.Repository.IRepository;
using VehicleRentingSystem.Models;
using VehicleRentingSystem.Models.ViewModels;

namespace VehicleRentingSystemWeb.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class ProfileController : Controller
    {
       
        private readonly IUnitOfWork _unitOfWork;
        public ProfileController(IUnitOfWork unitOfWork )
        {
            _unitOfWork = unitOfWork;
            
        }
        public IActionResult Index(string? userId)
        {
            if (userId == null)
            {


                //getting logged user id

                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claimRole = claimsIdentity.FindFirst(ClaimTypes.Role);
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
               
                //getting logged user id end

                
              if(claimRole.Value=="Driver")
                {
                    
                    var post = _unitOfWork.Bid.GetAll(u => u.ApplicationUserId == claim.Value);
                    if (post.Count()!= null)
                    {
                        foreach(var item in post)
                        {
                            if(item.Confirmed==true)
                            {
                                var confirmedPost = _unitOfWork.Post_Car.GetFirstOrDefault(u => u.Id == item.PostId); 
                                confirmedPost.Confirm=true;
                            }
                        }
                    }
                    

                    var n = post.Count();
                    int?[] postId = new int?[n];
                    int i = 0;
                    foreach (var item in post)
                    {
                        postId[i] = item.PostId;
                        i++;
                    }
                    int?[] unique = postId.Distinct().ToArray();
                    ProfileVM profileVM = new ProfileVM();


                    
                    T[] InitializeArray<T>(int length) where T : new()
                    {
                        T[] array = new T[length];
                        for (int i = 0; i < length; ++i)
                        {
                            array[i] = new T();
                        }

                        return array;
                    }

                    Post_Car[] objPostList = InitializeArray<Post_Car>(unique.Length);
                    
                    for (int j = 0; j < unique.Length; j++)
                    {
                        objPostList[j] = _unitOfWork.Post_Car.GetFirstOrDefault(u => u.Id == unique[j]);

                    }

                    profileVM.post_Cars = objPostList;

                    profileVM.applicationUser = _unitOfWork.ApplicationUser.GetAll(u => u.Id == claim.Value);
                    return View(profileVM);
                }
                else 
                {
                    ProfileVM profileVM = new()
                    {
                        post_Cars = _unitOfWork.Post_Car.GetAll(u => u.ApplicationUserId == claim.Value),
                        applicationUser = _unitOfWork.ApplicationUser.GetAll(u => u.Id == claim.Value),
                        bidHistory = _unitOfWork.Bid.GetAll(u => u.Confirmed == true),
                        

                    };
                    return View(profileVM);
                }

                

            }
            else
            {
                var post=_unitOfWork.Bid.GetAll(u=>u.ApplicationUserId==userId);
                var n=post.Count();
                int?[] postId = new int?[n];
                int i = 0;
                foreach(var item in post) 
                {
                    postId[i] = item.PostId;
                    i++;
                }
                int?[] unique = postId.Distinct().ToArray();
                ProfileVM profileVM = new ProfileVM();
               

                
                T[] InitializeArray<T>(int length) where T : new()
                {
                    T[] array = new T[length];
                    for (int i = 0; i < length; ++i)
                    {
                        array[i] = new T();
                    }

                    return array;
                }

                Post_Car[] objPostList = InitializeArray<Post_Car>(unique.Length);
                
                for (int j=0; j<unique.Length; j++)
                {
                    objPostList[j]= _unitOfWork.Post_Car.GetFirstOrDefault(u => u.Id == unique[j]);
                    
                }
              
                profileVM.post_Cars = objPostList;
                
                profileVM.applicationUser = _unitOfWork.ApplicationUser.GetAll(u => u.Id == userId);
                profileVM.showComplainButton = true;
                profileVM.DriverId = userId;
                return View(profileVM);

            }
            
        }


        //Get
        public IActionResult Complain( string? driverId)
        {

            Complain complain = new();
            complain.DriverUserId = driverId;
            return View(complain);

        }

        //POST 
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize]
        public IActionResult Complain(Complain obj)
        {
			//getting logged user id

			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end

            obj.ApplicationUserId = claim.Value;


			_unitOfWork.Complain.Add(obj);
			_unitOfWork.Save();


			return RedirectToAction(nameof(Index));

		}


    }
}

VehicleRentingSystemWeb/Views/Shared/_Layout.cshtml
@using VehicleRentingSystem.Utility;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VehicleRentingSystemWeb</title>
    <link rel="stylesheet" href="~/css/BootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/VehicleRentingSystemWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg " id="nav" style="background: linear-gradient(to right, #0f0c29, #302b63, #24243e); z-index:9999">
  <div class="container-fluid">
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="~/" style="color:azure">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item" >
                            <a class="nav-link " asp-area="User" asp-controller="Profile" asp-action="Index" style="color:azure">Profile</a>
        </li>
       
        <li class="nav-item">
                            <a class="nav-link " style="color:azure" asp-area="User" asp-controller="Post_Car" asp-action="Index">Car</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " style="color:azure" asp-area="Truck" asp-controller="Post_Truck" asp-action="Index">Truck</a>
        </li>
        @if(User.IsInRole(SD.Role_Admin))
        {
            <li class="nav-item">
                <a class="nav-link " style="color:azure" asp-area="Identity" asp-page="/Account/Register">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " style="color:azure" asp-area="Admin" asp-controller="User" asp-action="Index">UserList</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " style="color:azure" asp-area="Admin" asp-controller="User" asp-action="Complain">ComplainList</a>
            </li>
        }
       @* @if(User.IsInRole(SD.Role_Admin))
        {
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" style="color:azure">Admin</a>
              <div class="dropdown-menu">
              <a class="nav-link " asp-area="User" asp-controller="City" asp-action="Index">City</a>
              <a class="nav-link " asp-area="User" asp-controller="Post_Car" asp-action="Index">PostCar</a>
              <a class="nav-link " asp-area="User" asp-controller="Profile" asp-action="Index">Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Separated link</a>
              </div>
            </li>
        }*@
      </ul>
      <partial name="_LoginPartial" />
         @* <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>*@
    </div>
  </div>
</nav>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
@*<footer class=" border-top" style="
    
   left: 0;
   bottom: 0;
   width: 100%;
   margin-top:525px;
   
   
   
">
    <div class="container">
        &copy; 2022 - VehicleRentingSystem developed by C181044 and C181072 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>*@

@*<script type="text/javascript">
    var nav=document.getElementById('nav')
    window.onscroll=function(){
        if(window.pageYOffset>100)
        {
            nav.style.position="fixed";
            nav.style.top=0;
        }
        else{
            nav.style.position="absolute";
            nav.style.top=100;
        }
        
    }
</script>*@

VehicleRentingSystemWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
  
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.warning('@TempData["error"]')
    </script>
}