VehicleRentingSystemWeb/Areas/Truck/Controllers/Post_TruckController.cs
using VehicleRentingSystem.DataAccess;
using VehicleRentingSystem.DataAccess.Repository.IRepository;
using VehicleRentingSystem.Models;
using Microsoft.AspNetCore.Mvc;
using VehicleRentingSystem.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using System.Security.Cryptography;

namespace VehicleRentingSystemWeb.Areas.Truck.Controllers
{
    [Area("Truck")]
    [Authorize]
    public class Post_TruckController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;
        private object postTruckFromDbFirst;
        public Bid Bid { get; set; }

        public Post_TruckController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {


            IEnumerable<Post_Truck> objPostList = _unitOfWork.Post_Truck.GetAll();


            foreach (var item in objPostList)
            {
                //remaining time counting
                DateTime dateTime = DateTime.Now;

                TimeSpan remainingTime = dateTime.Subtract(item.TargetTime);


                if (remainingTime.Hours == 0 && remainingTime.Minutes < 0 || remainingTime.Hours == 1 && remainingTime.Minutes < 0)
                {
                    item.DewTime = Math.Abs(remainingTime.Minutes);
                }
                else
                {
                    item.DewTime = 0;
                    item.TimeOver = true;
                }

                //remaining time counting end


                var post = _unitOfWork.TruckBid.GetAll(u => u.TruckPostId == item.Id);
                foreach (var item2 in post)
                {
                    if (item2.Confirmed == true)
                    {

                        item.Confirm = true;
                    }
                }
            }

            PostVM postVM = new()
            {
                objPostTruck =  objPostList.OrderByDescending(u => u.Id),

            };
            return View(postVM);
        }

       
        //GET
        public IActionResult Create()
        {


            return View();
        }

        //POST 
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize]
        public IActionResult Create(Post_Truck obj, IFormFile file)
        {
            //getting logged user id

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end

            //countDown timer
            DateTime dateTime = DateTime.Now;
            obj.PostTime = dateTime;
            obj.TargetTime = dateTime.AddMinutes(30);

            //countDown timer end

            string wwwRootPath = _hostEnvironment.WebRootPath;
			if (file != null)
			{
				string fileName = Guid.NewGuid().ToString();
				var uploads = Path.Combine(wwwRootPath, @"images/products");
				var extension = Path.GetExtension(file.FileName);
				//copying file in the product folder inside wwwroot
				using (var filestreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
				{
					file.CopyTo(filestreams);
				}
				//copying file in the product folder end
				obj.ImageUrl = @"\images\products\" + fileName + extension;
			}

			obj.ApplicationUserId = claim.Value;

          
                _unitOfWork.Post_Truck.Add(obj);
                _unitOfWork.Save();
               

            return RedirectToAction(nameof(Index));

        }

        

        public IActionResult Auction(int postId)
        {
            double? lowest;
            IEnumerable<TruckBid>? bidList = _unitOfWork.TruckBid.GetAll(u => u.TruckPostId == postId);
            if (bidList.Count() != 0)
            {
                lowest = bidList.Min(u => u.Bidding);
            }
            else
            {
                lowest = 0;
            }


            TruckBid truckbid = new TruckBid()
            {
                TruckPostId = postId,
                MinBid=lowest,
            };




            ////var categoryFromDbFirst = _unitOfWork.Bid.GetFirstOrDefault(u => u.PostId == postId);
            //IEnumerable<Bid> bidsFromDb = _unitOfWork.Bid.GetAll(u => u.PostId == postId);
            ////int minBid = bidsFromDb.Min(u => u.Bidding);
            //if (bidsFromDb == null)
            //{
            //    Bid bid = new Bid()
            //    {
            //        PostId = postId,
            //    };
            //    return View(bid);
            //}
            //else
            //{
            //    int minBid = bidsFromDb.Min(u => u.Bidding);
            //    Bid bidObj = new Bid()
            //    {
            //        PostId = postId,
            //        Bidding = minBid,
            //    };




            //    return View(bidObj);
            //}
            return View(truckbid);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize]
        public IActionResult Auction(TruckBid bid)
        {
            //getting logged user id

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end

            bid.ApplicationUserId = claim.Value;

            
            _unitOfWork.TruckBid.Add(bid);
            
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        
        public IActionResult Plus(TruckBid bidObj,  int truckpostId)
        {
            //getting logged user id

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end

            bidObj.ApplicationUserId = claim.Value;
            
            IEnumerable<TruckBid> bidsFromDb = _unitOfWork.TruckBid.GetAll(u => u.TruckPostId == truckpostId);
            int minBid = bidsFromDb.Min(u => u.Bidding);

            bidObj.Bidding=minBid+100;
            bidObj.TruckPostId = truckpostId;
            _unitOfWork.TruckBid.Add(bidObj);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Minus(TruckBid bidObj, int truckpostId)
        {
            //getting logged user id

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end

            bidObj.ApplicationUserId = claim.Value;
            

            IEnumerable<TruckBid> bidsFromDb = _unitOfWork.TruckBid.GetAll(u => u.TruckPostId == truckpostId);
            int minBid = bidsFromDb.Min(u => u.Bidding);

            bidObj.Bidding = minBid - 100;
            bidObj.TruckPostId = truckpostId;
            _unitOfWork.TruckBid.Add(bidObj);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult BiddingHistory(int truckpostId)
        {
            //IEnumerable<TruckBid> truckbidHistory = _unitOfWork.TruckBid.GetAll(u => u.TruckPostId == truckpostId, includeProperties: "ApplicationUser");


            //return View(truckbidHistory);

            IEnumerable<TruckBid> biddings = _unitOfWork.TruckBid.GetAll(u => u.TruckPostId == truckpostId, includeProperties: "ApplicationUser");

            // return View(bidHistory);

            TruckBiddingHistoryVM biddingHistory = new()
            {
                bidHistory = _unitOfWork.TruckBid.GetAll(u => u.TruckPostId == truckpostId, includeProperties: "ApplicationUser"),

            };
            foreach (var bookedChecking in biddings)
            {
                if (bookedChecking.Confirmed == true)
                {
                    biddingHistory.booked = true;
                }
                //else
                //{
                //    biddingHistory.booked = false;
                //}

            }

            return View(biddingHistory);
        }

        

        public IActionResult Confirm(int bidId)
        {
            //getting logged user id

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //getting logged user id end
            var bidItem = _unitOfWork.TruckBid.GetFirstOrDefault(u => u.Id == bidId);
            var postOwner=_unitOfWork.Post_Truck.GetFirstOrDefault(u => u.Id == bidItem.TruckPostId);
            if (postOwner.ApplicationUserId == claim.Value)
            {
                bidItem.Confirmed = true;
                _unitOfWork.TruckBid.Update(bidItem);
                _unitOfWork.Save();
            }
            else
            {
                throw new Exception("You dont have right to confirm");
            }

            return RedirectToAction(nameof(Index));
        }

        //Summary

        public IActionResult Summary(int postId)
        {
            Post_Truck post = _unitOfWork.Post_Truck.GetFirstOrDefault(u => u.Id == postId,  includeProperties: "ApplicationUser");
            TruckBid bidding = _unitOfWork.TruckBid.GetFirstOrDefault(u => u.TruckPostId == postId && u.Confirmed == true, includeProperties: "ApplicationUser");
            SummaryVM summary = new()
            {
                postTruck = post,
                bidTruck = bidding,
            };

            return View(summary);
        }

    }
}

VehicleRentingSystemWeb/Areas/Truck/Views/Post_Truck/Auction.cshtml
@model VehicleRentingSystem.Models.TruckBid 
<body style="background-image: url('../../../images/background images/auction.jpg');background-size: 90%;">
    <form method="post" style="margin-top: 11%">
        <input hidden asp-for="TruckPostId" />


        <div class=" mt-5 bg-light text-dark d-flex justify-content-center align-items-center border border-2 border-info rounded" style="background: linear-gradient(to right, #83a4d4, #b6fbff);">




           @* @if (User.IsInRole("Driver"))
            {*@
                <div class=" row p-3  " role="group" style="background: linear-gradient(to right, #83a4d4, #b6fbff);">
                    <div class="col-2 rounded-circle ">
                        <a asp-controller="Post_Truck" asp-action="Plus" asp-route-truckpostId="@Model.TruckPostId" class="btn btn-success rounded-circle">
                            <i class="bi bi-plus fs-4 fw-bold" style="color:azure">+</i>
                        </a> &nbsp;
                    </div>

                    <div class=" col-8 row pl-2">
                        <div class="col-6 text-primary"><h4>Count</h4></div>
                        <div class=" col-6 "><input asp-for="Bidding" class="form-control" /></div>
                    </div>
                    <div class="col-2 ">
                        <a asp-controller="Post_Truck" asp-action="Minus" asp-route-truckpostId="@Model.TruckPostId" class="btn btn-info rounded-circle">
                            <i class="bi bi-dash  fs-4 fw-bold">-</i>
                        </a>
                    </div>

                </div>
           @* }*@

            <div class=" ps-lg-2  m-2 d-flex  border border-2 border-info rounded " style="background: linear-gradient(to right, #83a4d4, #b6fbff);">
                <div class="row  align-items-center ">
                    <div class="col-6 pe-5 " style="color:white"><h4>Lowest Bid</h4></div>
                    <div class=" col-6 pe-5  " style="color:#0007C4"><p><h2>@Model.MinBid</h2></p></div>
                </div>
            </div>

        </div>


        <div class="card-footer">
            <div class="row p-5">
                <div class="col-12 col-md-4 pb-1">
                    <a class="btn btn-success form-control  btn-square btn-lg" style="height:50px;  background: linear-gradient(to right, #136a8a, #267871);" asp-action="Index">Back to Feed</a>
                </div>
                @if (User.IsInRole("Driver"))
                {
                    <div class="col-12 col-md-4 pb-1">

                        <button type="submit" value="Add to Cart" class=" btn-square btn-lg form-control" style="height:50px; color:white ; background: linear-gradient(to right, #0f2027, #203a43, #2c5364);">Add</button>

                    </div>
                }
                <div class="col-12 col-md-4 pb-1">
                    <a asp-area="Truck" asp-controller="Post_Truck" asp-action="BiddingHistory" asp-route-truckpostId="@Model.TruckPostId" class="btn form-control  btn-square btn-lg" style="height:50px; color:white;  background: linear-gradient(to right, #000046, #1cb5e0);">Bidding history</a>
                </div>
            </div>
        </div>




    </form>
</body>

VehicleRentingSystemWeb/Areas/Truck/Views/Post_Truck/BiddingHistory.cshtml
@using System.Collections;
@using VehicleRentingSystem.Models;


@* @model IEnumerable<TruckBid>*@
@model VehicleRentingSystem.Models.ViewModels.TruckBiddingHistoryVM





<form method="post">
    <br />

    <div class="container mt-5">
        <div class="card">
            <div class="card-header bg-dark text-light ml-0">
            </div>


            <div class="card-body">
                @foreach (var item in Model.bidHistory)
                {
                    <div class=" d-flex align-items-center">
                        <div class="col-12 text-sm-center col-lg-5  row">

                            <div class="col-6 col-sm-4 col-lg-4 pt-2">


                                

                                @if (User.IsInRole("User") && Model.booked == false)
                                {

                                    <div class="w-75 btn-group" role="group">
                                        <a asp-action="Confirm" asp-route-bidId="@item.Id" class="btn btn-primary">
                                            <i class="bi bi-plus-square">Confirm</i>
                                        </a>

                                    </div>

                                }
                                @if (User.IsInRole("User") && Model.booked == true)
                                {
                                    @if (item.Confirmed == null)
                                    {
                                        <div class="w-75 btn-group" role="group">
                                            <a asp-action="Confirm" asp-route-bidId="@item.Id" class="btn btn-danger disabled">
                                                <i class="bi bi-plus-square">Lost</i>
                                            </a>

                                        </div>
                                    }
                                    else
                                    {
                                        <div class="w-75 btn-group" role="group">
                                            <a asp-action="Confirm" asp-route-bidId="@item.Id" class="btn btn-success disabled">
                                                <i class="bi bi-plus-square">Confirmed</i>
                                            </a>

                                        </div>
                                    }

                                }

                            </div>
                        </div>
                        <div class="col-12 text-sm-center col-lg-4 text-lg-left">
                            <h5><strong>@item.ApplicationUser.Name</strong></h5>

                        </div>
                        <div class="col-12 text-sm-center col-lg-4 text-lg-left">
                            <h5><strong>@item.Bidding</strong></h5>

                        </div>




                    </div>
                    <hr />
                }

            </div>

        </div>
    </div>

</form>

VehicleRentingSystemWeb/Areas/Truck/Views/Post_Truck/Create.cshtml
@model VehicleRentingSystem.Models.Post_Truck
<div class="row" style="margin-top:10%">
	<div class="col-5">
		<form method="post" asp-action="Create" enctype="multipart/form-data">


			<div class="row">
				<div class="col-10">
					<div class="border rounded-3  p-3 mt-4 row" style=" box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);">
						<div class="col-12 pb-2">

							<hr style="background-color:darkmagenta" />
						</div>
						@*<div asp-validation-summary="All"></div>*@
						<div class="mb-3" >
							<label style="color:indigo" asp-for="PickUpLocation"></label>
							<input asp-for="PickUpLocation" class="form-control" style=" box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);" />
							<span asp-validation-for="PickUpLocation" class="text-danger"></span>
						</div>
						<div class="mb-3">
							<label style="color:indigo" asp-for="DropOutLoaction"></label>
							<textarea asp-for="DropOutLoaction" class="form-control" style=" box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);"></textarea>
							<span asp-validation-for="DropOutLoaction" class="text-danger"></span>
						</div>
						<div class="mb-3 col-6">
							<label style="color:indigo" asp-for="ProductName"></label>
							<input asp-for="ProductName" class="form-control" style=" box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);" />
							<span asp-validation-for="ProductName" class="text-danger"></span>
						</div>
						<div class="mb-3 col-6">
							<label style="color:indigo" asp-for="PickUpDate"></label>
							<input type="datetime-local" asp-for="PickUpDate" class="form-control" style=" box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);" />
							<span asp-validation-for="PickUpDate" class="text-danger"></span>
						</div>
						<div class="mb-3 ">
							<label style="color:indigo" asp-for="ImageUrl">Product Image</label>
							<input type="file" name="file" class="form-control" style=" box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);" />
							
						</div>
						<div class="mb-3">
							<label style="color:indigo" asp-for="Product_Des"></label>
							<textarea asp-for="Product_Des" class="form-control" style=" box-shadow: 0 3px 10px rgb(0 0 0 / 0.2);"></textarea>
							<span asp-validation-for="Product_Des" class="text-danger"></span>
						</div>




						<button type="submit" class="btn btn-primary" style="width:150px; ">Create</button>

						<a asp-controller="Post_Truck" asp-action="Index" class="btn btn-secondary" style="width:150px;">
							Back to Feed
						</a>
					</div>
				</div>
			</div>




		</form>
	</div>
	<div class="col-7 p-5" style="background-image: url('../../../images/background images/truckpost.jpg');background-size: 100%; background-repeat:no-repeat; background-position:center">
	</div>

</div>

@*server side validation*@

@section scripts{
	@{
		<partial name="_ValidationScriptsPartial" />

	}


}

VehicleRentingSystemWeb/Areas/Truck/Views/Post_Truck/Index.cshtml
@model VehicleRentingSystem.Models.ViewModels.PostVM

<div class=" " style="margin-top:8%">
    @if (User.IsInRole("User"))
    {
        <div class=" text-center pt-2">
            <a asp-controller="Post_Truck" asp-action="Create" class="btn" style="background: linear-gradient(to right, #2c3e50, #4ca1af); color:white">
                <i class="bi bi-plus-circle-dotted"></i>  Create new Post
            </a>
        </div>
    }
    @foreach (var post in Model.objPostTruck)
    {
        <div class=" ">
            <div class=" p-2 ">
                <div class="p-1 ">
                    <div class="" style="background: linear-gradient(to right, #83a4d4, #b6fbff); width:100%; height:100%;">


                        <div class=" text-white row overflow-hidden p-2  " style="width:100%; height:100%">
                            <div class=" col-6  " style="  display: flex;
                                                            flex-direction:column;
                                                              justify-content: center;
                                                              align-items: center; ">
                                <div class=" text-start">
                                    <p class="card-title  " style="color:#00FF33"><b style="color:white">Pickup Location:</b> @post.PickUpLocation</p>
                                    <p class="card-title  text-danger"><b style="color:white">Dropout Location:</b> @post.DropOutLoaction</p>
                                    <p class="card-title  ">Product Name: <b>@post.ProductName</b></p>
                                    <p class="card-title  ">Pickup Date: <b>@post.PickUpDate</b></p>
                                    <p class="text-black card-title">@Html.Raw(post.Product_Des)</p>
                                    @if (post.TimeOver != true)
                                    {

                                        <h2 class="card-title  ">Remaining Time: <b>@post.DewTime</b></h2>

                                           
                                    }
                                    else
                                    {
                                        
                                                <h2 class="card-title  " style="color:maroon">Time Over </h2>

                                           
                                    }
                                </div>
                               
                               
                            </div>
                            <div class=" col-6 p-3 " style=" height:300px; ">
                                <img src="@post.ImageUrl" class=" rounded" style="width:100%; height:100% "/>
                            </div>

                        </div>
                        @if(post.Confirm==true)
                        {
                            <div class="row">
                            <div class="col-md-6">
                                    <a asp-area="Truck" asp-controller="Post_Truck" asp-action="BiddingHistory" class="btn form-control  btn-square btn-lg" asp-route-truckpostId="@post.Id" style="height:50px; color:white;  background: linear-gradient(to right, #ed213a, #93291e);">
                                   Confirmed & Go to history
                                </a>
                            </div>
                            <div class="col-md-6">
                                    <a asp-area="Truck" asp-controller="Post_Truck" asp-action="Summary" class="btn  form-control btn-square btn-lg" style=" background: linear-gradient(to right, #ed213a, #93291e); color:white" asp-route-postId="@post.Id">
                                    Ride Summary
                                </a>
                            </div>
                            </div>
                            
                        }

                        else if (User.IsInRole("User"))
                        {
                            <a asp-area="Truck" asp-controller="Post_Truck" asp-action="BiddingHistory" asp-route-truckpostId="@post.Id" class="btn form-control  btn-square btn-lg" style="height:50px; color:white;  background: linear-gradient(to right, #360033, #0b8793);">
                                Bidding history
                            </a>
                        }
                        else if (User.IsInRole("Driver"))
                        {
                            if (post.TimeOver == true)
                            {
                                <a asp-area="Truck" asp-controller="Post_Truck" asp-action="BiddingHistory" class="btn  form-control" style=" background: linear-gradient(to right, #ed213a, #93291e); color:white" asp-route-postId="@post.Id">
                                    Go to history
                                </a>
                            }
                            else
                            {
                                <a asp-area="Truck" asp-controller="Post_Truck" asp-action="Auction" class="btn  form-control" style="background: linear-gradient(to right, #360033, #0b8793); color:white" asp-route-postId="@post.Id">
                                    Go For Bid
                                </a>
                            }
                        }
                    </div>

                </div>

            </div>

        </div>

    }
</div>

VehicleRentingSystemWeb/Areas/Truck/Views/Post_Truck/Summary.cshtml
@model VehicleRentingSystem.Models.ViewModels.SummaryVM


<section class="h-100 h-custom mt-5" style="background-color: #eee;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <div class="card border-top border-bottom border-3" style="border-color:darkblue !important;">
                    <div class="card-body p-5">

                        <p class="lead fw-bold mb-5" style="color:darkblue;">Ride details</p>

                        <div class="row">
                            <div class="col mb-3">
                                <p class="small text-muted mb-1">Date</p>
                                <p>@Model.postTruck.PickUpDate</p>
                            </div>
                            <div class="col mb-3">
                                <p class="small text-muted mb-1">Driver Name</p>
                                <p>@Model.bidTruck.ApplicationUser.Name</p>
                            </div>
                        </div>

                        <div class="mx-n5 px-5 py-4" style="background-color: #f2f2f2;">
                            <div class="row">
                                <div class="col-md-6 col-lg-6">
                                    <p>Pickup Location:</p>
                                </div>
                                <div class="col-md-6 col-lg-6">
                                    <p>@Model.postTruck.PickUpLocation</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">Dropout Location:</p>
                                </div>
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">@Model.postTruck.DropOutLoaction</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">Product name:</p>
                                </div>
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">@Model.postTruck.ProductName</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">Product owner:</p>
                                </div>
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">@Model.postTruck.ApplicationUser.PhoneNumber</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">Driver mobile:</p>
                                </div>
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">@Model.bidTruck.ApplicationUser.PhoneNumber</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">Amount to pay:</p>
                                </div>
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">@Model.bidTruck.Bidding</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">Tax:</p>
                                </div>
                                <div class="col-md-6 col-lg-6">
                                    <p class="mb-0">0.00</p>
                                </div>
                            </div>

                        </div>

                        <div class="row my-4">

                            <div class="col-md-8 col-lg-9">
                                <p class="lead fw-bold mb-0">Sub Total:</p>
                            </div>
                            <div class="col-md-4 col-lg-3">
                                <p class="lead fw-bold mb-0">@Model.bidTruck.Bidding Tk</p>
                            </div>
                        </div>



                        @*<p class="mt-4 pt-2 mb-0">Want any help? <a href="#!" style="color: #f37a27;">Please contact
                        us</a></p>*@

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}